name: Continue On Error Test

on:
  push:
    branches: [main]

jobs:
  will-fail-but-continue:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: This step will fail
        run: exit 1

      - name: This step should still run
        run: echo "I still ran even though the previous step failed!"
